### ISSUE TITLE
Option to keep just the most recent trace

### ISSUE THREAD

**Issue by johnlvogt** [LLNL/STAT#28]
We have a situation where the user is trying to diagnose a problem that is causing the node to crash.    Stat could potentially record what the program was doing moments before the crash, but ideally it would only store the final result received from each node.   There is a --traces argument to stat-cl, but I believe that limits the results to the first traces.

**Comment by lee218llnl** [comment]
I'm not exactly sure what you are asking for. Do you want to gather a trace when a crash is detected? You should be able to get that information if a core file is generated. STAT doesn't really have a way to intercept a job that is failing. Nor do I think it is particularly useful to constantly gather traces throughout the job since that will not show where it crashed. Let me know exactly what you are proposing and then we can determine if STAT is the proper tool for the job. We handle hangs a lot better than crashes.

**Comment by johnlvogt** [comment]
The idea isn't to intercept a job that is failing, just capturing what is was doing just before it failed; at least what it was doing up to the sampling interval of time before it failed.   

One way of looking at that is to say that it's just stat running as usual except only keeping just the most recent trace from each rank.

I'm not sure even if the original request is useful since the application shouldn't be able to bring down a node.      It's more along that lines of thinking if a very small extension could leverage STAT for a new use.

**Comment by johnlvogt** [comment]
Even if it's just me creating a one-off for the person to try out.

**Comment by lee218llnl** [comment]
on the surface I can see what you would like to accomplish, but knowing STAT and how stack traces work, I have my doubts as to how useful such an extension would be. Even if you sample every 1/10th of a second, the last stack trace gathered is very unlikely to provide clues as to the root cause of a crash that occurs 1/10th of a second later. Traditional debuggers with breakpoints and fancy features like replay/reversible debugging would be much more useful for cases like this.

While I hate to turn down your request, I don't think I can justify the effort in implementing this. We can discuss this further if you like and I'm open to any PRs if you think this worth implementing yourself. Let me know what you think.

**Comment by johnlvogt** [comment]
No problem; sometime you just have to throw out an idea and see it triggers anything.    I thought it might dovetail in with diagnosing a hang where only the last trace is significant; but that's probably better done with the delay argument that's already there.

I also doubt that state of the application could explain a node dying; that's not how an OS is supposed to work.
